version: "3"
services:
  redis:
    image: "redis:5"
    ports:
      - 6379:6379
  mongodb_container:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
