GET http://localhost:8080/api/fetcher
Accept: application/json

###

GET http://localhost:8080/api/fetcher/0
Accept: application/json
###

DELETE http://localhost:8080/api/fetcher/0
Accept: application/json

###
POST http://localhost:8080/api/fetcher
Content-Type: application/json

{
        "url":"https://latozradiem.pl/api/articles",
        "interval":9
}